test:
	gradle build --daemon
	java -jar build/libs/sudocv-0.1.0.jar test_data/game2.txt

run:
	java -jar build/libs/sudocv-0.1.0.jar test_data/game2.txt

runall:
	java -jar build/libs/sudocv-0.1.0.jar test_data/game2.txt
	java -jar build/libs/sudocv-0.1.0.jar test_data/game3.txt
	java -jar build/libs/sudocv-0.1.0.jar test_data/game5.txt
